
# Site settings

url: "https://udnisap.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"


# Google tracking id to track your visitors

google-tracking-id: "UA-70479214-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

web-app-mode: True

# Icons for Web App mode 

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

#############
# HTML Head #
#############

author: "Pasindu Perera"
lang: "en"
title: "{ Pasindu Perera }"
favicon: "/img/favicon.ico"
description: "Blog and website of Pasindu Perera, blogging mainly for tech. Opinions expressed are mine."
keywords: "Pasindu Perera, Blog, Findings, Captures, Tech"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/pasinduperera.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Mathematics"
  - text: "React, React-native"
  - text: "Webpack, Grunt, Gulp, Bower, npm, ES6, ES7, Babel"
  - text: "Angular, Ember, Elm, Sencha, ExtJS, Web Assembly, Rx"
  - text: "NodeJS, Express, Sails, Meteor"
  - text: "MongoDB, CouchDB, Mysql, Elastic Search"
  - text: "Selenium, Webdriver.io, Zombie, PhantomJS, JSDom, Cheerio"
  - text: "Git"
  - text: "Java, Spring, Guice"
  - text: "Python, Ruby on Rails"
  - text: "Bash, sed, grep, fifo, zsh, tmux, vim, xorg, openbox"
  - text: "Jenkins, Sonar, ESLint, Travis"
  - text: "Jest, Mocha, Chi, Jasmine, Cucumber"
  - text: "Metasploit, John the Reaper, XSS"
  - text: "Firebase, Parse"
  - text: "Heroku, Openshift, CloudControl, AWS"
  - text: "Docker, Puppet, Apache, Tomcat"
  - text: "Yii, Zend, Symphony, Codeigniter, CakePHP"
  - text: "ElectronJS, Cordova, Ionic, Sencha Touch"
  - text: "Piano, Guitar, Drums"
  - text: "Badminton, Chess"
  - text: "Machine learning, Data mining, Information retrieval, Algorithms"

########
# Blog #
########

# post-preview-words: 96
#
# paginate: 5
#
# fb-share: True
# twitter-share: True
# reddit-share: True
# google-plus-share: True
# linkedin-share: True
# pinterest-share: True
# vkontakte-share: True
# disqus-shortname: "udnisap"

###############
# Life Events #
###############

events:
  - image: "/img/career/Cake.png"
    date: "December 2015 - Today"
    description: "*Cake.net*


    Associate Tech Lead"
  - image: "/img/career/TadHack.png"
    date: "August 2014"
    description: "*TADHack Global Hackathon*


    Winner
    "
  - image: "/img/career/Leapset.jpg"
    date: "March 2014 - December 2015"
    description: "*Leapset*


    Software Engineer"

  - image: "/img/career/graduated.png"
    date: "August 2009 - March 2014"
    description: "*Compute Science and Engineering, University of Moratuwa*


    First Class Honours"

  - image: "/img/career/Ideamart.jpg"
    date: "October 2013"
    description: "*Dialog Ideamart Hackathon*


    Winner
    "
  - image: "/img/career/99x.png"
    date: "January 2013 - March 2013"
    description: "*99X Technologies*


    Software Engineer"

  - image: "/img/career/Thinkcube.png"
    date: "May 2012 - September 2012"
    description: "*Thinkube Systems*


    Trainee Software Engineer"

  - image: "/img/career/IEEExtream.png"
    date: "2010, 2011, 2012"
    description: "*IEEExtream Global Programming competition*


    Top 50 in the World
    "

  - image: "/img/career/IMO2008.png"
    date: "August 2008"
    description: "*International Mathematical Olympiad*


    Madrid, Spain
    "
  - image: "/img/career/IMO2007.png"
    date: "August 2007"
    description: "*International Mathematical Olympiad*


    Hanoi, Vietnam
    "
  - image: "/img/career/WRO.jpg"
    date: "March 2004"
    description: "*World Robotic Olympiad*


    Singapore"

# First image of the Career timeline
career-img: "/img/career/default.png"

##################
# Contact layout #
##################

email: "perera.pasindu@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/udnisap"
  - title: "twitter"
    url: "https://twitter.com/udnisap"
  - title: "github"
    url: "https://github.com/udnisap"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/udnisap"
  - title: "soundcloud"
    url: "https://soundcloud.com/udnisap"
  - title: "skype"
    url: "skype://pasindur"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
